#  Spam Classification


##  Details
Spam refers to unwanted email, often in the form of advertisements. In the literature, an email that is **not** spam is called *ham*. Most email providers offer automatic spam filtering, where spam emails will be moved to a separate inbox based on their contents. Of course this requires being able to scan an email and determine whether it is spam or ham, a classification problem. 

You are welcome to use tools from libraries such as `numpy` and `scipy` to write your classifier.

Note that while you may use tools such as the `cdist` function above, you **can not** import code which builds entire models. This includes but is not limited to use of a library like `scikit-learn`. 

The training data is described below and has 1000 rows. There is also a 500 row set of test data. These are functionally identical to the training data, they are just in a separate csv file to encourage you to split out your training and test data. You should consider how to best make use of all available data without overfitting and may wish to consider tools such as cross validation. This might be used, for example, to help decide what value of $k$ to use for k-nearest neighbour.

## Part One
In this part you will write the code which builds the classifier. 

The cell below loads the training data into a variable called `training_spam`.

In [1]:
import numpy as np

training_spam = np.loadtxt(open("data/training_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam training data set:", training_spam.shape)
print(training_spam)

Shape of the spam training data set: (1000, 55)
[[1 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]]


In [4]:
import pandas as pd

pd.DataFrame(training_spam)

0   1   2   3   4   5   6   7   8   9   ...  45  46  47  48  49  50  51  \
0     1   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   1   0   
1     0   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   1   0   0   0   0  ...   1   0   0   0   0   1   0   
3     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4     0   1   0   0   0   0   0   0   0   0  ...   1   0   0   0   1   1   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
995   0   0   0   0   0   0   0   0   0   0  ...   1   0   0   0   0   0   0   
996   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
997   0   0   0   0   0   0   0   0   0   0  ...   1   0   0   0   0   1   0   
998   1   1   1   1   0   1   1   0   1   0  ...   0   0   1   0   0   1   0   
999   1   0   0   1   0   0   1   1   0   0  ...   0   0   0   0   0   0   0   

     52  53  54  
0     0   0   0  
1     1   0   0  
2     1   0   0  
3     1   0   0  
4     0   0   0  
..   ..  ..  ..  
995   1   0   0  
996   0   0   0  
997   0   0   1  
998   1   1   0  
999   1   1   1  

[1000 rows x 55 columns]

Your training set consists of 1000 rows and 55 columns. Each row corresponds to one email message. The first column is the _response_ variable and describes whether a message is spam `1` or ham `0`. The remaining 54 columns are _features_ that you will use to build a classifier. These features correspond to 54 different keywords (such as "money", "free", and "receive") and special characters (such as ":", "!", and "$"). A feature has the value `1` if the keyword appears in the message and `0` otherwise.

As mentioned there is also a 500 row set of *test data*. It contains the same 55 columns.

In [ ]:
testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam testing data set:", testing_spam.shape)
print(testing_spam)

Write all of the code for your classifier below this cell. There is some very rough skeleton code in the cell directly below. You may insert more cells below this if you wish.

### Submission Requirements
Your code must provide a variable with the name `classifier`. This object must have a method called `predict` which takes input data and returns class predictions. The input will be a single $n \times 54$ numpy array, your classifier should return a numpy array of length $n$ with classifications. There is a demo in the cell below, and a test you can run before submitting to check your code is working correctly.

Your code must run on our machines in under 60 seconds. If you wish to train a more complicated model (e.g. neural network) which will take longer, you are welcome to save the model's weights as a file and then load these in the cell below so we can test it. You must include the code which computes the original weights, but this must not run when we run the notebook – comment out the code which actually executes the routine and make sure it is clear what we need to change to get it to run. Remember that we will be testing your final classifier on additional hidden data.

In [ ]:
# This skeleton code simply classifies every input as ham
#
# Here you can see there is a parameter k that is unused, the
# point is to show you how you could set up your own. You might
# also pass in extra data via a train method (also does nothing
# here). Modify this code as much as you like so long as the 
# accuracy test in the cell below runs.

class SpamClassifier:
    def __init__(self, k):
        self.k = k
        
    def train(self):
        pass
        
    def predict(self, data):
        return np.zeros(data.shape[0])
    

def create_classifier():
    classifier = SpamClassifier(k=1)
    classifier.train()
    return classifier

classifier = create_classifier()

In [ ]:
# Write all of the code for your classifier above this cell.

# This cell will run the test data through the classifier and print the accuracy. 
# The skeleton code above classifies every row as ham, but once you have written
# your own classifier you can run this cell again to test it. So long as your code 
# sets up a variable called classifier with a method called predict, the test code 
# will be able to run. 

# You may want to create another verison of this cell for your own tests, especially
# if you choose to split the training and test data differently from the default 
# 1000/500 split.

# However you *must* ensure this version still runs before submitting.

testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
test_data = testing_spam[:, 1:]
test_labels = testing_spam[:, 0]

predictions = classifier.predict(test_data)
accuracy = np.count_nonzero(predictions == test_labels)/test_labels.shape[0]
print(f"Accuracy on test data is: {accuracy}")

## Part Two
In this part you will write a short discussion and analysis of your implementation in the cell below. 

* Please answer the following questions in your answer:
 * What supervised learning technique did you use?
 * How did you train it? How did you split training and test data? (If relevant.)
 * What accuracy percentage do you think your classifier will get on the *hidden* data?
* You may also wish to discuss the following points:
 * Discuss the measured accuracy of your classifier in the context of the spam filtering problem.
 * For any parameters that were chosen by hand, explain your choices.
 * How could you further improve performance? (For any definition of performance.)

YOUR ANSWER HERE – double click to edit, write in markdown, run cell to render

### Test Cell
The cell below contains hidden tests for part one, please do not modify or delete it.

In [ ]:
# This is a test cell. Please do not modify or delete.